version: '3.1'

services:

  mysql-srv:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: viaformation2024!
      MYSQL_DATABASE: livre-jeu
      MYSQL_USER: db_user
      MYSQL_PASSWORD: viaformation2024!
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1