services:
    web:
        build: './build/php/'
        ports:
            - "8003:443"
        volumes:
            - .:/var/www/livre-jeu
        links:
            - db:db
    db:
        build: './build/mysql/'
        volumes:
            - ~/.docker/mysql:/var/lib/mysql
        ports:
            - "3023:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=viaformation2024
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8073:80"
        links:
            - db:db
# ###> symfony/mailer ###
#     mailer:
#         image: axllent/mailpit
#         ports:
#             - "1025"
#             - "8025"
#         environment:
#             MP_SMTP_AUTH_ACCEPT_ANY: 1
#             MP_SMTP_AUTH_ALLOW_INSECURE: 1